--PL/SQL에서 출력함수인 DBMS_OUTPUT_LINE 사용시 출력용
SET SERVEROUTPUT ON;

--PL/SQL 기본문법
DECLARE
    DATA EMP%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('PL/SQL 시작..........');
    
    SELECT *
      INTO DATA
      FROM EMP
     WHERE EMPNO = '2001';
     
     DBMS_OUTPUT.PUT_LINE(DATA.ENAME || ', ' ||DATA.JOB);
END;
/


--프로시저
CREATE OR REPLACE PROCEDURE InsertEMP
(
    P_ENAME IN VARCHAR2
)
AS
    P_EMPNO CHAR(4);        --P_EMPNO EMP.EMPNO%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('InsertEMP 시작...');
--    INSERT INTO EMP (EMPNO, ENAME, HIREDATE)
--    VALUES (EX_EMPNO_SEQ.NEXTVAL, P_ENAME, SYSDATE);

    SELECT EX_EMPNO_SEQ.NEXTVAL
      INTO P_EMPNO
      FROM DUAL;
    
    DBMS_OUTPUT.PUT_LINE('직원번호는 ' || P_EMPNO);
    
    INSERT INTO EMP (EMPNO, ENAME, HIREDATE)
    VALUES (P_EMPNO, P_ENAME, SYSDATE);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('이름은 ' || P_ENAME);
END;
/

--프로시저 실행
EXEC InsertEMP('펭수');

SELECT MAX(EMPNO) FROM EMP;
SELECT * FROM EMP ORDER BY EMPNO DESC;