--회원테이블 생성
CREATE TABLE TBL_USER
(
    USER_ID varchar2(20) NOT NULL,
    USER_PWD VARCHAR2(20) NULL,
    USER_NAME VARCHAR2(30) NULL,
    USER_EMAIL VARCHAR2(50) NULL,
    STATUS CHAR(1) NULL,
    REG_DATE DATE NULL
);

COMMENT ON TABLE TBL_USER IS '회원';
COMMENT ON COLUMN TBL_USER.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN TBL_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN TBL_USER.USER_NAME IS '사용자명';
COMMENT ON COLUMN TBL_USER.USER_EMAIL IS '사용자 이메일';
COMMENT ON COLUMN TBL_USER.STATUS IS '사용여부(Y:사용, N:정지)';
COMMENT ON COLUMN TBL_USER.REG_DATE IS '등록일';

CREATE UNIQUE INDEX XPK_USER ON TBL_USER(USER_ID ASC);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TBL_USER';
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'TBL_USER';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'TBL_USER';
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'TBL_USER';

--로그인용 데이터 생성
INSERT INTO TBL_USER VALUES ('test', '1234', '홍길동', 'ttt@sist.co.kr', 'Y', SYSDATE);

SELECT * FROM TBL_USER;