SELECT USER_ID,
       NVL(USER_PWD, '') USER_PWD,
       NVL(USER_NAME, '') USER_NAME,
       NVL(USER_EMAIL, '') USER_EMAIL,
       NVL(STATUS, 'N') STATUS,
       NVL(TO_CHAR(REG_DATE, 'YYYY.MM.DD HH24:MI:SS'), '') REG_DATE
  FROM TBL_USER
 WHERE USER_ID = 'test';